import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/db';
function clean(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,14000)}
function isVacancy(text:string){const t=text.toLowerCase();const jobTerms=['responsibilities','requirements','required','preferred','experience','skills','vacancy','job','role','position','candidate','we offer','salary','remote','full-time','part-time','обязанности','требования','вакансия','кандидат','опыт','навыки','puesto','requisitos','responsabilidades','experiencia'];const hits=jobTerms.filter(w=>t.includes(w)).length;return text.trim().length>80&&hits>=2}
function langCode(language:string){const l=(language||'').toLowerCase();if(l.includes('russian'))return'ru';if(l.includes('spanish'))return'es';if(l.includes('german'))return'de';return'en'}
function extract(text:string){const dict=['SQL','Python','JavaScript','React','Next','Product','Roadmap','Roadmapping','User Research','Agile','Scrum','Stakeholder','Security','SIEM','SOC','Cloud','AWS','Azure','API','Testing','Growth','PLG','Compliance','Incident','Risk','Linux','Windows','EDR','XDR','DLP','ServiceNow','ITIL'];const keywords=dict.filter(k=>text.toLowerCase().includes(k.toLowerCase()));const title=(text.match(/(?:Senior|Lead|Middle|Junior)?\s*(?:Product Manager|Security Analyst|SOC Analyst|UX Researcher|Project Manager|Business Analyst|Incident Manager|Security Engineer|Service Manager)/i)?.[0]||text.split('\n').find(x=>x.trim().length>5&&x.trim().length<90)||'Parsed vacancy');const company=(text.match(/(?:at|company|компания)\s+([A-ZА-Я][\wА-Яа-я.-]+)/i)?.[1]||'Target company');return {title,company,responsibilities:text.split(/[.!?]\s|\n/).filter(s=>/own|lead|manage|develop|analyz|coordinate|support|implement|monitor|investigate|управл|анализ|координир|разработ|внедр/i.test(s)).slice(0,10),requiredSkills:keywords.slice(0,12),preferredSkills:keywords.slice(12,18),senioritySignals:(text.match(/senior|lead|ownership|stakeholder|strategy|руковод|лид|стратег/ig)||[]).slice(0,8),softSkills:(text.match(/communication|stakeholder|collaboration|ownership|leadership|коммуникац|ответствен/ig)||[]).slice(0,8),tone:'professional, concise, evidence-driven',marketSignals:['Use concise ATS-friendly structure','Avoid unsupported claims','Prioritize measurable impact'],keywords:keywords.length?keywords:['responsibilities','skills','experience'],sourceText:text.slice(0,9000)}}
export async function POST(req:NextRequest){const session=await getServerSession(authOptions);if(!session?.user)return NextResponse.json({error:'Unauthorized'},{status:401});const userId=(session.user as any).id as string;const {url,text,language,targetMarket}=await req.json();let source=text||'';try{if(url){const hh=url.match(/hh\.(ru|kz|uz|by)\/vacancy\/(\d+)/);if(hh){const r=await fetch(`https://api.hh.ru/vacancies/${hh[2]}`,{headers:{'User-Agent':'AI Resume Generator MVP'}});const j=await r.json();source=[j.name,j.employer?.name,j.description,j.key_skills?.map((x:any)=>x.name).join(', ')].filter(Boolean).join('\n');}else{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'}});source=clean(await r.text())||source;}}}catch{source=text||''}if(!isVacancy(source))return NextResponse.json({error:'This does not look like a vacancy. Paste a real job description with responsibilities, requirements, skills, company or role details.'},{status:400});const analysis=extract(source);const job=await prisma.jobPosting.create({data:{userId,title:analysis.title,sourceUrl:url||null,sourceText:source,language:langCode(language||'English'),targetMarket:targetMarket||'EU',analysis,companySignals:analysis.marketSignals||[]}});await prisma.historyItem.create({data:{userId,type:'vacancy',title:analysis.title,details:analysis.company,payload:{jobPostingId:job.id,analysis}}});return NextResponse.json({analysis,job})}
